# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_pastelaria
      - MARIADB_DATABASE=bitnami_pastelaria
    ports:
      - '3306:3306'
  pastelaria:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_pastelaria
      - DB_DATABASE=bitnami_pastelaria
    volumes:
      - './pastelaria:/app'
    depends_on:
      - mariadb
